### ISSUE TITLE
Include the PSR-7 Request and Method Utilities

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/adrenaline#12]
See mwop's blog post about the [PSR-7 Request and Method Utilities](https://mwop.net/blog/2017-01-26-http-message-util.html).

**Comment by dropdevcoding** [comment]
I will have a look until monday

**Comment by shochdoerfer** [comment]
Not sure if it makes sense for Adrenaline or Adroit or both. I leave the decision up to you ;)
