### ISSUE TITLE
JsonResponder and TwigResponder don't respect status set in payload

### ISSUE THREAD

**Issue by dropdevcoding** [bitExpert/adrenaline#2]
In JsonResponder the status set in payload is not respected, since it's implemented like that:

``` php
return $response->withStatus(200);
```

This should be fixed by using the same logic used in other responders:

``` php
$status = $payload->getStatus() ?: 200;
return $response->withStatus($status);
```

**Comment by shochdoerfer** [comment]
Good catch!

**Comment by dropdevcoding** [comment]
I recently detected the same problem in TwigResponder
