### ISSUE TITLE
Stratigility upgrade shows warning

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/adrenaline#9]
After upgrading Stratigility and running the unit tests the following warning shows up:

```
Usage of error middleware is deprecated as of 1.3.0, and will be removed in 2.0.0; please 
see https://docs.zendframework.com/zend-stratigility/migration/to-v2/ for details on how 
to update your application to remove this message.
```

Looks like we need to change our implementation a bit.

**Comment by shochdoerfer** [comment]
@dropdevcoding Can you take care of this issue, please?

**Comment by dropdevcoding** [comment]
Sorry for delay, didn't recognize for some reason. I will have a look this weekend!
